### ISSUE TITLE
web/admin inport missing org.iottree.pro.*, and "IPro cannot be resolved to a type", "ProManager cannot be resolved"

### ISSUE THREAD

**Issue by wisdomleo** [bambooww/iot-tree#11]
Dear Bambooww,

See below  web/admin/index.jsp, can't import "org.iottree.pro.*":
![image](https://github.com/user-attachments/assets/a78790b3-7d72-4c7e-82ce-e4538aa3fb84)

IPro and ProManager cannot be resolved to a type:
![image](https://github.com/user-attachments/assets/62aab14d-e6b0-4af0-9850-c27baedcf0de)

Was it deleted in version 1.7.2 ?

Best Regards,
Leo Ma

**Comment by bambooww** [comment]
These are some special driver packages, you can put the iottree-ext-pro-1.7.3. jar file from the release version into your system. Or delete this code

**Comment by wisdomleo** [comment]
> These are some special driver packages, you can put the iottree-ext-pro-1.7.3. jar file from the release version into your system. Or delete this code

OK，Thanks a lot!!!
