### ISSUE TITLE
ext-parent pom.xml missing modules: ext-opcda and ext-pro

### ISSUE THREAD

**Issue by wisdomleo** [bambooww/iot-tree#6]
~\ext-parent\pom.xml：
Cannot resolve symbol 'ext-opcda': 28
Cannot resolve symbol 'ext-pro':30
![ext-parent-error](https://github.com/user-attachments/assets/36ea4c0d-7c09-4604-b55f-88dab27fe3f1)

**Comment by bambooww** [comment]
You can delete it and continue building

**Comment by wisdomleo** [comment]
OK, thanks a lot !!!  Build completed successfully with 8 warnings in 31 sec!
![build-successfully](https://github.com/user-attachments/assets/6a68865a-a1e4-4bc4-90a4-ea64bb5068eb)
