### ISSUE TITLE
Run web/main, input user/psd then no any actions, chrome F12 console show "Failed to load resource: the server responded with a status of 404 ()"

### ISSUE THREAD

**Issue by wisdomleo** [bambooww/iot-tree#7]
Dear bambooww,

I met a problem after building project and artifacts, run with tomcat 9, but there is a problem, looks like missing resource  _js/*.js,
![image](https://github.com/user-attachments/assets/7bc5c9ef-aad0-43c7-afd1-f65b236e9adc)
![image](https://github.com/user-attachments/assets/8aaf44ef-1a25-452b-ace3-18420892c35e)

I tried to copy the folder "_js" to any pathes I can, like:
    1. %tomcat_root%/webapps
    3. /webapps/main_war
    4.  /webapps/main_war/login
unfortunatelly, always show failed to load resource, could you please help me, thanks a lot in advice!!!

by the way, where the foledr "_js, _iottree, _ui" from? why there is no this three forders in source code(src code zip)?

Best Regards,
Leo Ma

**Comment by bambooww** [comment]
Please download release *.zip file.  you cannot find _js in it.

**Comment by wisdomleo** [comment]
thanks it works now! I copy the _js\* to the artifacts folder \out\artifacts\admin_Web_exploded\ forder.

**Comment by wisdomleo** [comment]
> Please download release *.zip file. you can find _js in it.

thanks it works now! I copy the _js* to the artifacts folder \out\artifacts\admin_Web_exploded\ forder.
