### ISSUE TITLE
HTTP Status 500 - Message can't get include TLD:[java.io.FileNotFoundException]JAR resource[/wb_tag]

### ISSUE THREAD

**Issue by wisdomleo** [bambooww/iot-tree#8]
Dear bambooww,

chrome error page as below:
![image](https://github.com/user-attachments/assets/550b4224-871d-467d-9d62-e68a250c96c8)

I tried to copy the wb_tag.tld file from "_iot-tree-1.7.2.zip\\ web\admin\WEB-INF\wb_tag.tld_" to IDEA build artifacts out folder "_D:\idea-workspace\iot-tree-1.7.2-src\iot-tree-1.7.2\out\artifacts\admin_Web_exploded\WEB-INF\wb_tag.tld_", 
but it not works. 
Could you please help? Thanks in advice!!!

Best Refards,
Leo Ma

**Comment by wisdomleo** [comment]
IDEA Project Structure ad below:
![image](https://github.com/user-attachments/assets/c049c3fc-63d9-48ae-9920-715cc1721d4b)

iot-tree tomcat runs normally:
![image](https://github.com/user-attachments/assets/bfc5b70c-32d8-4035-b29d-d5f97844691e)

**Comment by bambooww** [comment]
I am not familiar with the idea. Can you configure the dev environment to be the same as the release version? The embedded Tomcat will determine which webapp directories to load based on the config. xml ‘s <webapps> element. That is to say, when starting IoT tree, you don't need to use Idea's web support, as it can actually cause a lot of trouble.

**Comment by wisdomleo** [comment]
> I am not familiar with the idea. Can you configure the dev environment to be the same as the release version? The embedded Tomcat will determine which webapp directories to load based on the config. xml ‘s element. That is to say, when starting IoT tree, you don't need to use Idea's web support, as it can actually cause a lot of trouble.

Yes, it's a lot of trouble. lol. 
But, I am not only want to use iot-tree, but also want to learning and developing ther whole java web project. So I use dev tool IDEA(Developed by JetBrain company, IDEA full name is "IntelliJ IDEA", is one popular java development tool);

By the way, which dev tool you used to develop iot-tree? Eclipse or others?

config.xml, I noticed iot-tree use maven pom.xml, which config.xml you fingered?

**Comment by bambooww** [comment]
I use Eclipse and do not have any specialized support for web development because Tomcat is embedded and I have complete control over loading the web app myself. IDEA is definitely possible, you just need to treat this project as a regular Java app

**Comment by wisdomleo** [comment]
> I use Eclipse and do not have any specialized support for web development because Tomcat is embedded and I have complete control over loading the web app myself. IDEA is definitely possible, you just need to treat this project as a regular Java app

ok, thanks!
I checked and found the root cause is web.xml, no defined the tag of "taglib", I modified as *.zip\\web.xml as below:
-----------------------------------------------
    <jsp-config>
        <taglib>
            <taglib-uri>wb_tag</taglib-uri>
            <taglib-location>/WEB-INF/wb_tag.tld</taglib-location>
        </taglib>
    </jsp-config>
-----------------------------------------------
and it was fixed!!! Thanks a lot anyway!!!
